#include "analysis_pipeline/wfd5/stages/identify_time_of_lyso_hit.h"

#include <TParameter.h>
#include <spdlog/spdlog.h>

ClassImp(identify_time_of_lyso_hit)

identify_time_of_lyso_hit::identify_time_of_lyso_hit() = default;

void identify_time_of_lyso_hit::OnInit() {
    example_config_value_ = parameters_.value("example_value", 0.0);
    spdlog::debug("[{}] Initialized with example_value={}", Name(), example_config_value_);
}

void identify_time_of_lyso_hit::Process() {
    auto param = std::make_unique<TParameter<double>>("example_product", example_config_value_);

    auto pdp = std::make_unique<PipelineDataProduct>();
    pdp->setName("example_product");
    pdp->setObject(std::move(param));
    pdp->addTag("example_tag");
    pdp->addTag("autogenerated_stage");

    getDataProductManager()->addOrUpdate("example_product", std::move(pdp));
    spdlog::debug("[{}] Produced example_product with value {}", Name(), example_config_value_);
}

